version: '3.8'

networks:
  public_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.70.128/26

services:
  # --- 5G CORE (AMF) ---
  oai-amf:
    image: oai-amf:v1.5.0
    container_name: oai-amf
    environment:
      - MCC=208
      - MNC=99
    networks:
      public_net:
        ipv4_address: 192.168.70.132

# --- HAPS gNodeB SERVİSİ ---
  oai-gnb:
    image: oai-gnb:latest
    container_name: haps-gnb
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    volumes:
      # Yan yana duran dosyaları Doğrudan konteynere bağlar
      - ./gnb.haps.conf:/opt/oai-gnb/etc/gnb.conf
      - ./haps_channel.conf:/opt/oai-gnb/etc/haps_channel.conf
    environment:
      - RFSIMULATOR=server
    command: >
      /opt/oai-gnb/bin/nr-softmodem 
      -O /opt/oai-gnb/etc/gnb.conf 
      --rfsim 
      --conf_file /opt/oai-gnb/etc/haps_channel.conf
    networks:
      public_net:
        ipv4_address: 192.168.70.140

  # --- HAPS NR UE SERVİSİ ---
  oai-nr-ue:
    image: oai-nr-ue:latest
    container_name: haps-ue
    cap_add:
      - NET_ADMIN
    environment:
      - RFSIMULATOR=192.168.70.140
    command: >
      /opt/oai-nr-ue/bin/nr-uesoftmodem 
      -r 106 --numerology 1 -C 3619200000 
      --rfsim 
      --rfsimulator.serveraddr 192.168.70.140 
      --rfsimulator.prop_delay 66 
      --rfsimulator.options chan_mod 
      --channelmod.model_name rfsimu_channel_ue0
    depends_on:
      - oai-gnb
    networks:
      public_net:
        ipv4_address: 192.168.70.150
