# SPDX-License-Identifier: LicenseRef-CSSL-1.0

channelmod = {
  max_chan = 10;
  modellist = "modellist_rfsimu_haps";

  modellist_rfsimu_haps = (
    {
      model_name     = "rfsimu_channel_enB0";
      type           = "AWGN";                # HAPS baskın LoS bağlantısı için AWGN/Rician (İstenirse SAT_LEO_TRANS kalabilir)
      noise_power_dB = -105;                 # Gürültü seviyesi
      pl_dB          = 110.0;                 # 20 km Serbest Uzay Yol Kaybı (FSPL @ 3.5 GHz)
      forget_factor  = 0.0;
    },
    {
      model_name     = "rfsimu_channel_ue0";
      type           = "AWGN";
      noise_power_dB = -105;
      pl_dB          = 110.0;
      forget_factor  = 0.0;
    }
  );
};
