channelmod = {
  max_chan = 10;
  modellist = "haps_channel_list";
};

haps_channel_list = (
  {
    model_name     = "rfsimu_channel_enB0";
    type           = "HAPS";         # C koduna eklediğimiz HAPS modeli
    ploss_dB       = 110.0;          # 20 km Serbest Uzay Yol Kaybı (FSPL)
    noise_power_dB = -105.0;         # Termal gürültü tabanı (dBFS)
    forgetfact     = 0.0;
    offset         = 0;
    ds_tdl         = 0.0;
  }
);
